### ISSUE TITLE
ModuleNotFoundError (No module named 'numpy.testing.nosetester')

### ISSUE THREAD

**Issue by carlosal1015** [scikit-monaco/scikit-monaco#15]
When we run python runtests.py we have the following message error
```python
/tmp/makepkg/python-scikit-monaco-git/src/scikit-monaco/runtests.py:58: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import imp
Building, see build.log...
Build OK
Running unit tests for skmonaco
NumPy version 1.23.0
NumPy relaxed strides checking option: True
NumPy is installed in /usr/lib/python3.10/site-packages/numpy
Python version 3.10.5 (main, Jun  6 2022, 18:49:26) [GCC 12.1.0]
nose version 1.3.7
/usr/lib/python3.10/site-packages/numpy/testing/_private/nosetester.py:448: DeprecationWarning: 

  `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
  of the deprecation of `distutils` itself. It will be removed for
  Python >= 3.12. For older Python versions it will remain present.
  It is recommended to use `setuptools < 60.0` for those Python versions.
  For more details, see:
    https://numpy.org/devdocs/reference/distutils_status_migration.html 


  from ...distutils import cpuinfo
EEEEE
======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'numpy.testing.nosetester')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3.10/site-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/usr/lib/python3.10/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3.10/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.10/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.10/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/tmp/makepkg/python-scikit-monaco-git/src/scikit-monaco/build/testenv/lib/python3.10/site-packages/skmonaco/tests/test_from_points.py", line 5, in <module>
    from utils import assert_within_tol, run_module_suite
  File "/tmp/makepkg/python-scikit-monaco-git/src/scikit-monaco/build/testenv/lib/python3.10/site-packages/skmonaco/tests/utils.py", line 4, in <module>
    from numpy.testing.nosetester import import_nose
ModuleNotFoundError: No module named 'numpy.testing.nosetester'

======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'numpy.testing.decorators')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3.10/site-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/usr/lib/python3.10/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3.10/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.10/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.10/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/tmp/makepkg/python-scikit-monaco-git/src/scikit-monaco/build/testenv/lib/python3.10/site-packages/skmonaco/tests/test_importance.py", line 4, in <module>
    from numpy.testing.decorators import slow
ModuleNotFoundError: No module named 'numpy.testing.decorators'

======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'numpy.testing.nosetester')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3.10/site-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/usr/lib/python3.10/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3.10/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.10/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.10/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/tmp/makepkg/python-scikit-monaco-git/src/scikit-monaco/build/testenv/lib/python3.10/site-packages/skmonaco/tests/test_miser.py", line 5, in <module>
    from utils import run_module_suite
  File "/tmp/makepkg/python-scikit-monaco-git/src/scikit-monaco/build/testenv/lib/python3.10/site-packages/skmonaco/tests/utils.py", line 4, in <module>
    from numpy.testing.nosetester import import_nose
ModuleNotFoundError: No module named 'numpy.testing.nosetester'

======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'numpy.testing.nosetester')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3.10/site-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/usr/lib/python3.10/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3.10/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.10/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.10/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/tmp/makepkg/python-scikit-monaco-git/src/scikit-monaco/build/testenv/lib/python3.10/site-packages/skmonaco/tests/test_seed_generator.py", line 3, in <module>
    from utils import assert_within_tol, run_module_suite
  File "/tmp/makepkg/python-scikit-monaco-git/src/scikit-monaco/build/testenv/lib/python3.10/site-packages/skmonaco/tests/utils.py", line 4, in <module>
    from numpy.testing.nosetester import import_nose
ModuleNotFoundError: No module named 'numpy.testing.nosetester'

======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'numpy.testing.decorators')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3.10/site-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/usr/lib/python3.10/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3.10/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.10/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.10/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/tmp/makepkg/python-scikit-monaco-git/src/scikit-monaco/build/testenv/lib/python3.10/site-packages/skmonaco/tests/test_uniform.py", line 6, in <module>
    from numpy.testing.decorators import slow
ModuleNotFoundError: No module named 'numpy.testing.decorators'

----------------------------------------------------------------------
Ran 5 tests in 0.012s

FAILED (errors=5)
```

**Comment by Naereen** [comment]
Hi there,
Thanks for your interest in scikit-monaco! Sorry I never saw your issue before, I didn't have the notifications turned on here...
I saw this issue today on my side (see #17), I'll try to solve it.
But I'll probably won't have time until July... sorry.
Regards from France, @Naereen.
